config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'chatroom#index'
  get 'login', to: 'sessions#login'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  post 'message', to: 'messages#create'


  mount ActionCable.server, at: '/cable'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  validates :body , presence: true
  #to get the las created 20 massages
  scope :custom_display, -> { order(:created_at).last(20) }
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, length:{minimum: 3,maximum:15},
            uniqueness: {case_sensitive: false}
  has_many :messages
  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user , :logged_in?
  #to make available on  views and controller
  def current_user
   @current_user ||= User.find(session[:user_id]) if session[:user_id]
 #if current_user exist or equil to this user then keep going
    end

    def logged_in?
      !!current_user
      #to check if current_user is access, yes or no
    end

    def require_user
      if !logged_in?
        flash[:error] = "You must be logged in to perform that action"
        redirect_to login_path
    end
  end
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
  before_action :require_user
 def index
    @message = Message.new
   @messages = Message.custom_display
 end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :require_user
  def create
    message = current_user.messages.build(message_params)
    if message.save
      ActionCable.server.broadcast "chatroom_channel",
                  mod_message: message_render(message)
    end
  end

  private
  def message_params
    params.require(:message).permit(:body)
  end

  def message_render(message)
    render(partial: 'messages', locals: {message: message})
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :logged_in_redirect, only: [:new, :create]
  def new
  end
  def create
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
    session[:user_id] = user.id
    flash[:success] = "Welcome Back"
    redirect_to root_path
    else
      flash.now[:error]= "Enter a valid username and password"
      render 'login'
    end
  end
  def destroy
    session[:user_id]  = nil
    flash[:success] = "You logged out"
    redirect_to login_path
  end

  private

  def logged_in_redirect
    if logged_in?
      flash[:erorr] = "You are already lodded in"
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chatroom/index.html.erb
<h4 class="ui center aligned medium icon header">
  <i class="circular  coffee icon"></i>
  Say something
</h4>
<div class="ui two column grid">
  <div class="twelve wide column">
    <div class="ui fluid raised card chatbox">
      <div class="content" id="messages">
        <div class="ui feed" id="message-container">
        <%= render 'messages/messages' %>
        </div>
      </div>
      <div class=" extra content">
        <div class="">
          <%= form_for(@message, html: {class: "ui reply form", role: "form"}, url: message_path, remote: true) do |f| %>
            <div class="field">
            <div class="ui fluid primary icon input">
              <%= f.text_field :body  %>
              <%= f.button '<i class="bordered icon edit"></i>'.html_safe %>
            </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="four wide column">
    <div class="ui card chatbox">
      <div class="content">
        <div class="ui inverted vertical menu">
          <a class="active item">
            Home
          </a>
          <a class="item">
            Messages
          </a>
          <a class="item">
            Friends
          </a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_massages.html.erb
<% flash.each do |message_type, message_content| %>
  <div class="ui <%= message_type %> message transition">
    <i class="close icon"></i>
    <div class="header">
    <%= message_content %>
    </div>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="ui container">
    <a><%= link_to "Chatroom",root_path, class: "item" %></a>
  <a class="item">
    Messages
  </a>
  <div class="right menu">
    <div class="ui dropdown item">
      Account
      <i class="dropdown icon"></i>
      <div class="menu">
        <% if logged_in? %>
        <a><%= link_to "Logout",logout_path, methood: :delete, class: "item" %></a>
        <% else %>
        <a><%= link_to "Log in",login_path, class: "item" %></a>
        <a><%= link_to "Sign up",login_path, class: "item" %></a>
        <% end %>
      </div>
    </div>
      <% if !logged_in? %>
    <div class="item">
        <a><%= link_to "Log in",login_path, class: "ui primary button" %></a>
    </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Message Me</title>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <div class="ui inverted small menu">
    <%= render 'layouts/navigation' %>
    </div>
    <div class="ui container">
      <%= render 'layouts/massages'%>
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_messages.html.erb
<% @messages.each do |message| %>
  <div class="event">
    <div class="content">
      <div class="summary">
        <em><%= message.user.username %></em>
        :
        <em><%= message.body %></em>
      </div>
    </div>
  </div>
<% end %>